name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'          # Only trigger when something in /doc changes
  workflow_dispatch:      # Allows manual trigger if needed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'doc'         # This is the folder that will be deployed

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
